### ISSUE TITLE
Shaking Screen

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [GeekyAnts/nativebase-v3-kitchensink#20]
Under Windows 10 using Firefox (newest Version) when having a small screensize (for example: 1295 x 700) the screen is shaking.
For all other browsers and os it works like a charm.

This overflowX for web:
https://github.com/GeekyAnts/nativebase-v3-kitchensink/blob/fbe39d86ecc1c7de4c5e01b1c10263a9a0f1a13a/src/components/RootComponent.tsx#L30

causes that a div (class: css-view-1dbjc4n") flips between minView and minHeight or something. Well commenting out this line fixed the error.

**Comment by amars29** [comment]
@NilsBaumgartner1994 Above issue has been fixed. Please refer the following [commit](https://github.com/GeekyAnts/nativebase-v3-kitchensink/pull/14/commits/23ab5a362138c12ad7e1fe716b5e3e4da33f14fc) for details.

**Comment by NilsBaumgartner1994** [comment]
thanks
