### ISSUE TITLE
Web version not working

### ISSUE THREAD

**Issue by dhcmega** [GeekyAnts/nativebase-v3-kitchensink#23]
Hi
Steps to reproduce:

`% git clone git@github.com:GeekyAnts/nativebase-v3-kitchensink.git`
Cloning into 'nativebase-v3-kitchensink'...
Enter passphrase for key '/Users/diegohelmann/.ssh/id_rsa': 
Enter passphrase for key '/Users/diegohelmann/.ssh/id_rsa': 
remote: Enumerating objects: 2823, done.
remote: Counting objects: 100% (2823/2823), done.
remote: Compressing objects: 100% (1358/1358), done.
remote: Total 2823 (delta 1537), reused 2609 (delta 1344), pack-reused 0
Receiving objects: 100% (2823/2823), 1.45 MiB | 2.49 MiB/s, done.

`% yarn`
yarn install v1.22.15
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "expo > @unimodules/react-native-adapter@5.7.0" has incorrect peer dependency "react-native-web@~0.13.7".
warning " > react-native-web@0.17.1" has incorrect peer dependency "react@>=17.0.1".
warning " > react-native-web@0.17.1" has incorrect peer dependency "react-dom@>=17.0.1".
warning " > styled-components@5.3.0" has unmet peer dependency "react-is@>= 16.8.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 88.90s.

`% expo start`
Starting project at /Users/diegohelmann/ReactNativeProjects/nativebase-v3-kitchensink
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Some dependencies are incompatible with the installed expo package version:
 - expo-linear-gradient - expected version: ~8.4.0 - actual version installed: 9.1.0
 - react-native-svg - expected version: 12.1.0 - actual version installed: 12.1.1
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
Starting Metro Bundler

After hitting `w`
Web Bundling JavaScript [=============================================================   ] 95%Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

Web Bundling complete 13358ms
./src/config/map.tsx:670:19
Module not found: Can't resolve '../nb/components/basic/KeyboardAvoidingView/Kitchensink-Basic'
  668 |     components: [
  669 |       {
> 670 |         component: require('../nb/components/basic/KeyboardAvoidingView/Kitchensink-Basic'),
      |                   ^
  671 |         title: 'Basic',
  672 |         description: '',
  673 |       },
./src/config/map.tsx:192:19
Module not found: Can't resolve '../nb/components/primitives/ButtonGroup/basic'
  190 |       },
  191 |       {
> 192 |         component: require('../nb/components/primitives/ButtonGroup/basic'),
      |                   ^
  193 |         title: 'ButtonGroup',
  194 |         description: '',
  195 |       },

The caret is pointing at the start of the `require` word.

**Comment by amars29** [comment]
@dhcmega Running the script `node built-init` before expo start will solve the issue.

**Comment by dhcmega** [comment]
It worked. Thanks!
