### ISSUE TITLE
Example app doesn't work on latest Expo Go client

### ISSUE THREAD

**Issue by hlynurstef** [GeekyAnts/nativebase-v3-kitchensink#30]
It seems like the Expo app is not working in the latest Expo client on Android. It requires updating of the expo sdk to version 41.0.0 or higher and publishing it again.

<img src="https://user-images.githubusercontent.com/15615089/147709020-ff3f3ed5-bd5d-47d7-acb0-e1bacf1396e8.png" alt="screenshot" width="400"/>
<img src="https://user-images.githubusercontent.com/15615089/147709119-d5362c88-7027-47b5-93ab-80ec31aec25f.png" alt="screenshot" width="400"/>

**Comment by sfustar** [comment]
Hi, any updates on this issue?

**Comment by surajahmed** [comment]
@sfustar Thanks for pointing this out. We're working on it. Hope to fix this in the coming release.

**Comment by amars29** [comment]
Hi @hlynurstef, issue has been solved now.

**Comment by hlynurstef** [comment]
Thanks @amars29, I've tested it and it works now 🎉
